using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MarketTester
{
    public class ResourceKeys
    {
        public const string StringAppName = "StringAppName";
        public const string StringID = "StringID";
        public const string StringClOrdID = "StringClOrdID";
        public const string StringOrigClOrdID = "StringOrigClOrdID";
        public const string NameRadioButtonLimit = "NameRadioButtonLimit";
        public const string NameRadioButtonMarket = "NameRadioButtonMarket";
        public const string NameRadioButtonMarketToLimit = "NameRadioButtonMarketToLimit";
        public const string StringEnglish = "StringEnglish";
        public const string StringTurkish = "StringTurkish";

        public const string StringAccount = "StringAccount";
        public const string StringAccountAbbrvtd = "StringAccountAbbrvtd";
        public const string StringPrice = "StringPrice";
        public const string StringPriceAbbrvtd = "StringPriceAbbrvtd";
        public const string StringSymbol = "StringSymbol";
        public const string StringSymbolAbbrvtd = "StringSymbolAbbrvtd";
        public const string StringQuantity = "StringQuantity";
        public const string StringQuantityAbbrvtd = "StringQuantityAbbrvtd";
        public const string StringLimit = "StringLimit";
        public const string StringLimitAbbrvtd = "StringLimitAbbrvtd";
        public const string StringMarket = "StringMarket";
        public const string StringMarketAbbrvtd = "StringMarketAbbrvtd";
        public const string StringMarketToLimit = "StringMarketToLimit";
        public const string StringMarketToLimitAbbrvtd = "StringMarketToLimitAbbrvtd";
        public const string StringSend = "StringSend";
        public const string StringChannel = "StringChannel";
        public const string StringChannelAbbrvtd = "StringChannelAbbrvtd";
        public const string StringConnectionConfigurations = "StringConnectionConfigurations";
        public const string StringConnect = "StringConnect";
        public const string StringChannels = "StringChannels";
        public const string StringSide = "StringSide";
        public const string StringOrdType = "StringOrdType";
        public const string StringOrdTypeAbbrvtd = "StringOrdTypeAbbrvtd";
        public const string StringTimeInForce = "StringTimeInForce";
        public const string StringTimeInForceAbbrvtd = "StringTimeInForceAbbrvtd";
        public const string StringCumulativeQty = "StringCumulativeQty";
        public const string StringLastPx = "StringLastPx";
        public const string StringAvgPx = "StringAvgPx";
        public const string StringDate = "StringDate";
        public const string StringOrdStatus = "StringOrdStatus";
        public const string StringLastQty = "StringLastQty";
        public const string StringImported = "StringImported";
        public const string StringActiveSessions = "StringActiveSessions";
        public const string StringInactiveSessions = "StringInactiveSessions";
        public const string StringOrder = "StringOrder";
        public const string StringExport = "StringExport";
        public const string StringImport = "StringImport";
        public const string StringClear = "StringClear";
        public const string StringLanguage = "StringLanguage";
        public const string StringSettings = "StringSettings";
        public const string StringOkay = "StringOkay";
        public const string StringCancel = "StringCancel";
        public const string StringCancelAllOrders = "StringCancelAllOrders";
        public const string StringLineFormat = "StringLineFormat";
        public const string StringAnalyzers = "StringAnalyzers";
        public const string StringPickFile = "StringPickFile";
        public const string StringSave = "StringSave";
        public const string StringInputFile1 = "StringInputFile1";
        public const string StringInputFile2 = "StringInputFile2";
        public const string StringTools = "StringTools";
        public const string StringLogAnalyzers = "StringLogAnalyzers";
        public const string StringName = "StringName";
        public const string StringDelete = "StringDelete";
        public const string StringPick = "StringPick";
        public const string StringStartAnalysis = "StringStartAnalysis";
        public const string StringLineFormats = "StringLineFormats";
        public const string StringOutFilePath = "StringOutFilePath";
        public const string StringExportOrders = "StringExportOrders";
        public const string StringErrorPopupName = "StringErrorPopupName";
        public const string StringInvalidLineFormat = "StringInvalidLineFormat";
        public const string StringDestinationFilePath = "StringDestinationFilePath";
        public const string StringTag = "StringTag";
        public const string StringValue = "StringValue";
        public const string StringAdd = "StringAdd";
        public const string StringSelect = "StringSelect";
        public const string StringProtocolType = "StringProtocolType";
        public const string StringSchedule = "StringSchedule";
        public const string StringRemoveFromSchedule = "StringRemoveFromSchedule";
        public const string StringClearSchedule = "StringClearSchedule";
        public const string StringStartSchedule = "StringStartSchedule";
        public const string StringScheduler = "StringScheduler";
        public const string StringDelayMilliSecond = "StringDelayMilliSecond";
        public const string StringTagEmpty = "StringTagEmpty";
        public const string StringValueEmpty = "StringValueEmpty";
        public const string StringCantEditTag = "StringCantEditTag";
        public const string StringFixFreeFormat = "StringFixFreeFormat";
        public const string StringFile = "StringFile";
        public const string StringLoad = "StringLoad";
        public const string StringSchedules = "StringSchedules";
        public const string StringFailedAnalysis = "StringFailedAnalysis";
        public const string StringFileIsBeingUsed = "StringFileIsBeingUsed";
        public const string StringPleaseFillNameAndFormat = "StringPleaseFillNameAndFormat";
        public const string StringStartingAnalysis = "StringStartingAnalysis";
        public const string StringFinishedAnalysis = "StringFinishedAnalysis";
        public const string StringChannelNotConnectedWarning = "StringChannelNotConnectedWarning";
        public const string StringConfigPasswordNotSetWarning = "StringConfigPasswordNotSetWarning";
        public const string StringPleaseSelectAChannel = "StringPleaseSelectAChannel";
        public const string StringChannelNotConnected = "StringChannelNotConnected";
        public const string StringCannotParseDelayFromFile = "StringCannotParseDelayFromFile";
        public const string StringMsgType = "StringMsgType";
        public const string StringExpireDate = "StringExpireDate";
        public const string StringAllocID = "StringAllocID";
        public const string StringDeleteSchedule = "StringDeleteSchedule";
        public const string StringCantEditIdTags = "StringCantEditIdTags";
        public const string StringQuantityMultiplier = "StringQuantityMultiplier";
        public const string StringPriceOffset = "StringPriceOffset";
        public const string StringPriceOffsetEmpty = "StringPriceOffsetEmpty";
        public const string StringQuantityMultiplierEmpty = "StringQuantityMultiplierEmpty";
        public const string StringUnknownErrorOccured = "StringUnknownErrorOccured";
        public const string StringConnectionNotActive = "StringConnectionNotActive";
        public const string StringExportToCsv = "StringExportToCsv";
        public const string StringAppendToCsv = "StringAppendToCsv";
        public const string StringExportToXLSX = "StringExportToXLSX";
        public const string StringAppendToXLSX = "StringAppendToXLSX";
        public const string StringMessage = "StringMessage";
        public const string StringSavedMessages = "StringSavedMessages";
        public const string StringSaveMessage = "StringSaveMessage";
        public const string StringMessageName = "StringMessageName";
        public const string StringEnterAMessageName = "StringEnterAMessageName";
        public const string StringNoTagValuePairSet = "StringNoTagValuePairSet";
        public const string StringOnlyNewMessage = "StringOnlyNewMessage";
        
    }
}
